create table film (id bigint not null auto_increment, director varchar(255), episode_id integer not null, producer varchar(255), release_date datetime, title varchar(255), primary key (id)) type=MyISAM;
create table person (id bigint not null auto_increment, birth_year varchar(255), gender varchar(255), height varchar(255), mass varchar(255), name varchar(255), skin_color varchar(255), homeworld_id bigint, primary key (id)) type=MyISAM;
create table person_films (characters_id bigint not null, films_id bigint not null) type=MyISAM;
create table planet (id bigint not null auto_increment, climate varchar(255), diameter varchar(255), gravity varchar(255), name varchar(255), orbital_period varchar(255), population varchar(255), rotation_period varchar(255), surface_water varchar(255), terrain varchar(255), primary key (id)) type=MyISAM;
create table planet_films (planets_id bigint not null, films_id bigint not null) type=MyISAM;
create table planet_residents (planet_id bigint not null, residents_id bigint not null) type=MyISAM;
create table species (id bigint not null auto_increment, avg_height varchar(255), avg_lifespan varchar(255), classification varchar(255), designation varchar(255), eye_colors varchar(255), language varchar(255), name varchar(255), skin_colors varchar(255), homeworld_id bigint, primary key (id)) type=MyISAM;
create table species_films (species_id bigint not null, films_id bigint not null) type=MyISAM;
create table species_people (species_id bigint not null, people_id bigint not null) type=MyISAM;
create table starship (id bigint not null auto_increment, cost_in_credits varchar(255), crew varchar(255), length varchar(255), manufacturer varchar(255), max_atmosphering_speed varchar(255), max_megalights varchar(255), model varchar(255), name varchar(255), passengers varchar(255), starship_class varchar(255), primary key (id)) type=MyISAM;
create table starship_films (starships_id bigint not null, films_id bigint not null) type=MyISAM;
create table starship_pilots (starships_id bigint not null, pilots_id bigint not null) type=MyISAM;
create table vehicle (id bigint not null auto_increment, cost_in_credits varchar(255), crew varchar(255), length varchar(255), manufacturer varchar(255), max_atmosphering_speed varchar(255), model varchar(255), name varchar(255), passengers varchar(255), vehicle_class varchar(255), primary key (id)) type=MyISAM;
create table vehicle_films (vehicles_id bigint not null, films_id bigint not null) type=MyISAM;
create table vehicle_pilots (vehicles_id bigint not null, pilots_id bigint not null) type=MyISAM;
alter table person add constraint FK9xoqlm4cvgwol95469rqtauq4 foreign key (homeworld_id) references planet (id);
alter table person_films add constraint FK6v1bygbdvv02v072nh0mxkqpn foreign key (films_id) references film (id);
alter table person_films add constraint FKavfmyayv2v0yutn7qnh2o7wkm foreign key (characters_id) references person (id);
alter table planet_films add constraint FKj6xfpgdqqmb34j880l60nsfcw foreign key (films_id) references film (id);
alter table planet_films add constraint FKb7b8v6em5vxkmigjqqk3kxctv foreign key (planets_id) references planet (id);
alter table planet_residents add constraint FKhashmp7rcgqdvrbecjsh09m5r foreign key (residents_id) references person (id);
alter table planet_residents add constraint FK7j18qhysxpxcqtujirava927t foreign key (planet_id) references planet (id);
alter table species add constraint FKp61wjv50m3nfvoke36v174sn5 foreign key (homeworld_id) references planet (id);
alter table species_films add constraint FK2t8l5jefsmxfxsxy49poro10v foreign key (films_id) references film (id);
alter table species_films add constraint FKi5t8kxgr865bol115vhpcrsb8 foreign key (species_id) references species (id);
alter table species_people add constraint FK5uaqwr63ov7wd1an62sukw908 foreign key (people_id) references person (id);
alter table species_people add constraint FK7soq9pv3s6djgtxmb7431fgee foreign key (species_id) references species (id);
alter table starship_films add constraint FKpnmpsm2g9bir1km1nufbaor4i foreign key (films_id) references film (id);
alter table starship_films add constraint FKjmrtlhumxa8gkjt3ufjvr5u0c foreign key (starships_id) references starship (id);
alter table starship_pilots add constraint FKmg96tf6y6o5aqaucqj38ep9fl foreign key (pilots_id) references person (id);
alter table starship_pilots add constraint FKj8woi4aqnwlx2tay4w7saq83y foreign key (starships_id) references starship (id);
alter table vehicle_films add constraint FKs8cfkhvkn8cv4yaxbm1u1rih7 foreign key (films_id) references film (id);
alter table vehicle_films add constraint FKfl30g9l5ocqbg7p3k9w5v25fb foreign key (vehicles_id) references vehicle (id);
alter table vehicle_pilots add constraint FKqimn856lkidkyajfbi4mm3xvy foreign key (pilots_id) references person (id);
alter table vehicle_pilots add constraint FKep6tpw2kgcwsnlkr1pb4qqq16 foreign key (vehicles_id) references vehicle (id);
create table film (id bigint not null auto_increment, director varchar(255), episode_id integer not null, producer varchar(255), release_date datetime, title varchar(255), primary key (id)) type=MyISAM;
create table person (id bigint not null auto_increment, birth_year varchar(255), gender varchar(255), height varchar(255), mass varchar(255), name varchar(255), skin_color varchar(255), homeworld_id bigint, primary key (id)) type=MyISAM;
create table person_films (characters_id bigint not null, films_id bigint not null) type=MyISAM;
create table planet (id bigint not null auto_increment, climate varchar(255), diameter varchar(255), gravity varchar(255), name varchar(255), orbital_period varchar(255), population varchar(255), rotation_period varchar(255), surface_water varchar(255), terrain varchar(255), primary key (id)) type=MyISAM;
create table planet_films (planets_id bigint not null, films_id bigint not null) type=MyISAM;
create table planet_residents (planet_id bigint not null, residents_id bigint not null) type=MyISAM;
create table species (id bigint not null auto_increment, avg_height varchar(255), avg_lifespan varchar(255), classification varchar(255), designation varchar(255), eye_colors varchar(255), language varchar(255), name varchar(255), skin_colors varchar(255), homeworld_id bigint, primary key (id)) type=MyISAM;
create table species_films (species_id bigint not null, films_id bigint not null) type=MyISAM;
create table species_people (species_id bigint not null, people_id bigint not null) type=MyISAM;
create table starship (id bigint not null auto_increment, cost_in_credits varchar(255), crew varchar(255), length varchar(255), manufacturer varchar(255), max_atmosphering_speed varchar(255), max_megalights varchar(255), model varchar(255), name varchar(255), passengers varchar(255), starship_class varchar(255), primary key (id)) type=MyISAM;
create table starship_films (starships_id bigint not null, films_id bigint not null) type=MyISAM;
create table starship_pilots (starships_id bigint not null, pilots_id bigint not null) type=MyISAM;
create table vehicle (id bigint not null auto_increment, cost_in_credits varchar(255), crew varchar(255), length varchar(255), manufacturer varchar(255), max_atmosphering_speed varchar(255), model varchar(255), name varchar(255), passengers varchar(255), vehicle_class varchar(255), primary key (id)) type=MyISAM;
create table vehicle_films (vehicles_id bigint not null, films_id bigint not null) type=MyISAM;
create table vehicle_pilots (vehicles_id bigint not null, pilots_id bigint not null) type=MyISAM;
alter table person add constraint FK9xoqlm4cvgwol95469rqtauq4 foreign key (homeworld_id) references planet (id);
alter table person_films add constraint FK6v1bygbdvv02v072nh0mxkqpn foreign key (films_id) references film (id);
alter table person_films add constraint FKavfmyayv2v0yutn7qnh2o7wkm foreign key (characters_id) references person (id);
alter table planet_films add constraint FKj6xfpgdqqmb34j880l60nsfcw foreign key (films_id) references film (id);
alter table planet_films add constraint FKb7b8v6em5vxkmigjqqk3kxctv foreign key (planets_id) references planet (id);
alter table planet_residents add constraint FKhashmp7rcgqdvrbecjsh09m5r foreign key (residents_id) references person (id);
alter table planet_residents add constraint FK7j18qhysxpxcqtujirava927t foreign key (planet_id) references planet (id);
alter table species add constraint FKp61wjv50m3nfvoke36v174sn5 foreign key (homeworld_id) references planet (id);
alter table species_films add constraint FK2t8l5jefsmxfxsxy49poro10v foreign key (films_id) references film (id);
alter table species_films add constraint FKi5t8kxgr865bol115vhpcrsb8 foreign key (species_id) references species (id);
alter table species_people add constraint FK5uaqwr63ov7wd1an62sukw908 foreign key (people_id) references person (id);
alter table species_people add constraint FK7soq9pv3s6djgtxmb7431fgee foreign key (species_id) references species (id);
alter table starship_films add constraint FKpnmpsm2g9bir1km1nufbaor4i foreign key (films_id) references film (id);
alter table starship_films add constraint FKjmrtlhumxa8gkjt3ufjvr5u0c foreign key (starships_id) references starship (id);
alter table starship_pilots add constraint FKmg96tf6y6o5aqaucqj38ep9fl foreign key (pilots_id) references person (id);
alter table starship_pilots add constraint FKj8woi4aqnwlx2tay4w7saq83y foreign key (starships_id) references starship (id);
alter table vehicle_films add constraint FKs8cfkhvkn8cv4yaxbm1u1rih7 foreign key (films_id) references film (id);
alter table vehicle_films add constraint FKfl30g9l5ocqbg7p3k9w5v25fb foreign key (vehicles_id) references vehicle (id);
alter table vehicle_pilots add constraint FKqimn856lkidkyajfbi4mm3xvy foreign key (pilots_id) references person (id);
alter table vehicle_pilots add constraint FKep6tpw2kgcwsnlkr1pb4qqq16 foreign key (vehicles_id) references vehicle (id);
create table film (id bigint not null auto_increment, director varchar(255), episode_id integer not null, producer varchar(255), release_date datetime, title varchar(255), primary key (id)) type=MyISAM;
create table person (id bigint not null auto_increment, birth_year varchar(255), gender varchar(255), height varchar(255), mass varchar(255), name varchar(255), skin_color varchar(255), homeworld_id bigint, primary key (id)) type=MyISAM;
create table person_films (characters_id bigint not null, films_id bigint not null) type=MyISAM;
create table planet (id bigint not null auto_increment, climate varchar(255), diameter varchar(255), gravity varchar(255), name varchar(255), orbital_period varchar(255), population varchar(255), rotation_period varchar(255), surface_water varchar(255), terrain varchar(255), primary key (id)) type=MyISAM;
create table planet_films (planets_id bigint not null, films_id bigint not null) type=MyISAM;
create table planet_residents (planet_id bigint not null, residents_id bigint not null) type=MyISAM;
create table species (id bigint not null auto_increment, avg_height varchar(255), avg_lifespan varchar(255), classification varchar(255), designation varchar(255), eye_colors varchar(255), language varchar(255), name varchar(255), skin_colors varchar(255), homeworld_id bigint, primary key (id)) type=MyISAM;
create table species_films (species_id bigint not null, films_id bigint not null) type=MyISAM;
create table species_people (species_id bigint not null, people_id bigint not null) type=MyISAM;
create table starship (id bigint not null auto_increment, cost_in_credits varchar(255), crew varchar(255), length varchar(255), manufacturer varchar(255), max_atmosphering_speed varchar(255), max_megalights varchar(255), model varchar(255), name varchar(255), passengers varchar(255), starship_class varchar(255), primary key (id)) type=MyISAM;
create table starship_films (starships_id bigint not null, films_id bigint not null) type=MyISAM;
create table starship_pilots (starships_id bigint not null, pilots_id bigint not null) type=MyISAM;
create table vehicle (id bigint not null auto_increment, cost_in_credits varchar(255), crew varchar(255), length varchar(255), manufacturer varchar(255), max_atmosphering_speed varchar(255), model varchar(255), name varchar(255), passengers varchar(255), vehicle_class varchar(255), primary key (id)) type=MyISAM;
create table vehicle_films (vehicles_id bigint not null, films_id bigint not null) type=MyISAM;
create table vehicle_pilots (vehicles_id bigint not null, pilots_id bigint not null) type=MyISAM;
alter table person add constraint FK9xoqlm4cvgwol95469rqtauq4 foreign key (homeworld_id) references planet (id);
alter table person_films add constraint FK6v1bygbdvv02v072nh0mxkqpn foreign key (films_id) references film (id);
alter table person_films add constraint FKavfmyayv2v0yutn7qnh2o7wkm foreign key (characters_id) references person (id);
alter table planet_films add constraint FKj6xfpgdqqmb34j880l60nsfcw foreign key (films_id) references film (id);
alter table planet_films add constraint FKb7b8v6em5vxkmigjqqk3kxctv foreign key (planets_id) references planet (id);
alter table planet_residents add constraint FKhashmp7rcgqdvrbecjsh09m5r foreign key (residents_id) references person (id);
alter table planet_residents add constraint FK7j18qhysxpxcqtujirava927t foreign key (planet_id) references planet (id);
alter table species add constraint FKp61wjv50m3nfvoke36v174sn5 foreign key (homeworld_id) references planet (id);
alter table species_films add constraint FK2t8l5jefsmxfxsxy49poro10v foreign key (films_id) references film (id);
alter table species_films add constraint FKi5t8kxgr865bol115vhpcrsb8 foreign key (species_id) references species (id);
alter table species_people add constraint FK5uaqwr63ov7wd1an62sukw908 foreign key (people_id) references person (id);
alter table species_people add constraint FK7soq9pv3s6djgtxmb7431fgee foreign key (species_id) references species (id);
alter table starship_films add constraint FKpnmpsm2g9bir1km1nufbaor4i foreign key (films_id) references film (id);
alter table starship_films add constraint FKjmrtlhumxa8gkjt3ufjvr5u0c foreign key (starships_id) references starship (id);
alter table starship_pilots add constraint FKmg96tf6y6o5aqaucqj38ep9fl foreign key (pilots_id) references person (id);
alter table starship_pilots add constraint FKj8woi4aqnwlx2tay4w7saq83y foreign key (starships_id) references starship (id);
alter table vehicle_films add constraint FKs8cfkhvkn8cv4yaxbm1u1rih7 foreign key (films_id) references film (id);
alter table vehicle_films add constraint FKfl30g9l5ocqbg7p3k9w5v25fb foreign key (vehicles_id) references vehicle (id);
alter table vehicle_pilots add constraint FKqimn856lkidkyajfbi4mm3xvy foreign key (pilots_id) references person (id);
alter table vehicle_pilots add constraint FKep6tpw2kgcwsnlkr1pb4qqq16 foreign key (vehicles_id) references vehicle (id);
create table film (id bigint not null auto_increment, director varchar(255), episode_id integer not null, producer varchar(255), release_date datetime, title varchar(255), primary key (id)) type=MyISAM;
create table person (id bigint not null auto_increment, birth_year varchar(255), gender varchar(255), height varchar(255), mass varchar(255), name varchar(255), skin_color varchar(255), homeworld_id bigint, primary key (id)) type=MyISAM;
create table person_films (characters_id bigint not null, films_id bigint not null) type=MyISAM;
create table planet (id bigint not null auto_increment, climate varchar(255), diameter varchar(255), gravity varchar(255), name varchar(255), orbital_period varchar(255), population varchar(255), rotation_period varchar(255), surface_water varchar(255), terrain varchar(255), primary key (id)) type=MyISAM;
create table planet_films (planets_id bigint not null, films_id bigint not null) type=MyISAM;
create table planet_residents (planet_id bigint not null, residents_id bigint not null) type=MyISAM;
create table species (id bigint not null auto_increment, avg_height varchar(255), avg_lifespan varchar(255), classification varchar(255), designation varchar(255), eye_colors varchar(255), language varchar(255), name varchar(255), skin_colors varchar(255), homeworld_id bigint, primary key (id)) type=MyISAM;
create table species_films (species_id bigint not null, films_id bigint not null) type=MyISAM;
create table species_people (species_id bigint not null, people_id bigint not null) type=MyISAM;
create table starship (id bigint not null auto_increment, cost_in_credits varchar(255), crew varchar(255), length varchar(255), manufacturer varchar(255), max_atmosphering_speed varchar(255), max_megalights varchar(255), model varchar(255), name varchar(255), passengers varchar(255), starship_class varchar(255), primary key (id)) type=MyISAM;
create table starship_films (starships_id bigint not null, films_id bigint not null) type=MyISAM;
create table starship_pilots (starships_id bigint not null, pilots_id bigint not null) type=MyISAM;
create table vehicle (id bigint not null auto_increment, cost_in_credits varchar(255), crew varchar(255), length varchar(255), manufacturer varchar(255), max_atmosphering_speed varchar(255), model varchar(255), name varchar(255), passengers varchar(255), vehicle_class varchar(255), primary key (id)) type=MyISAM;
create table vehicle_films (vehicles_id bigint not null, films_id bigint not null) type=MyISAM;
create table vehicle_pilots (vehicles_id bigint not null, pilots_id bigint not null) type=MyISAM;
alter table person add constraint FK9xoqlm4cvgwol95469rqtauq4 foreign key (homeworld_id) references planet (id);
alter table person_films add constraint FK6v1bygbdvv02v072nh0mxkqpn foreign key (films_id) references film (id);
alter table person_films add constraint FKavfmyayv2v0yutn7qnh2o7wkm foreign key (characters_id) references person (id);
alter table planet_films add constraint FKj6xfpgdqqmb34j880l60nsfcw foreign key (films_id) references film (id);
alter table planet_films add constraint FKb7b8v6em5vxkmigjqqk3kxctv foreign key (planets_id) references planet (id);
alter table planet_residents add constraint FKhashmp7rcgqdvrbecjsh09m5r foreign key (residents_id) references person (id);
alter table planet_residents add constraint FK7j18qhysxpxcqtujirava927t foreign key (planet_id) references planet (id);
alter table species add constraint FKp61wjv50m3nfvoke36v174sn5 foreign key (homeworld_id) references planet (id);
alter table species_films add constraint FK2t8l5jefsmxfxsxy49poro10v foreign key (films_id) references film (id);
alter table species_films add constraint FKi5t8kxgr865bol115vhpcrsb8 foreign key (species_id) references species (id);
alter table species_people add constraint FK5uaqwr63ov7wd1an62sukw908 foreign key (people_id) references person (id);
alter table species_people add constraint FK7soq9pv3s6djgtxmb7431fgee foreign key (species_id) references species (id);
alter table starship_films add constraint FKpnmpsm2g9bir1km1nufbaor4i foreign key (films_id) references film (id);
alter table starship_films add constraint FKjmrtlhumxa8gkjt3ufjvr5u0c foreign key (starships_id) references starship (id);
alter table starship_pilots add constraint FKmg96tf6y6o5aqaucqj38ep9fl foreign key (pilots_id) references person (id);
alter table starship_pilots add constraint FKj8woi4aqnwlx2tay4w7saq83y foreign key (starships_id) references starship (id);
alter table vehicle_films add constraint FKs8cfkhvkn8cv4yaxbm1u1rih7 foreign key (films_id) references film (id);
alter table vehicle_films add constraint FKfl30g9l5ocqbg7p3k9w5v25fb foreign key (vehicles_id) references vehicle (id);
alter table vehicle_pilots add constraint FKqimn856lkidkyajfbi4mm3xvy foreign key (pilots_id) references person (id);
alter table vehicle_pilots add constraint FKep6tpw2kgcwsnlkr1pb4qqq16 foreign key (vehicles_id) references vehicle (id);
create table film (id bigint not null auto_increment, director varchar(255), episode_id integer not null, producer varchar(255), release_date datetime, title varchar(255), primary key (id)) type=MyISAM;
create table person (id bigint not null auto_increment, birth_year varchar(255), gender varchar(255), height varchar(255), mass varchar(255), name varchar(255), skin_color varchar(255), homeworld_id bigint, primary key (id)) type=MyISAM;
create table person_films (characters_id bigint not null, films_id bigint not null) type=MyISAM;
create table planet (id bigint not null auto_increment, climate varchar(255), diameter varchar(255), gravity varchar(255), name varchar(255), orbital_period varchar(255), population varchar(255), rotation_period varchar(255), surface_water varchar(255), terrain varchar(255), primary key (id)) type=MyISAM;
create table planet_films (planets_id bigint not null, films_id bigint not null) type=MyISAM;
create table planet_residents (planet_id bigint not null, residents_id bigint not null) type=MyISAM;
create table species (id bigint not null auto_increment, avg_height varchar(255), avg_lifespan varchar(255), classification varchar(255), designation varchar(255), eye_colors varchar(255), language varchar(255), name varchar(255), skin_colors varchar(255), homeworld_id bigint, primary key (id)) type=MyISAM;
create table species_films (species_id bigint not null, films_id bigint not null) type=MyISAM;
create table species_people (species_id bigint not null, people_id bigint not null) type=MyISAM;
create table starship (id bigint not null auto_increment, cost_in_credits varchar(255), crew varchar(255), length varchar(255), manufacturer varchar(255), max_atmosphering_speed varchar(255), max_megalights varchar(255), model varchar(255), name varchar(255), passengers varchar(255), starship_class varchar(255), primary key (id)) type=MyISAM;
create table starship_films (starships_id bigint not null, films_id bigint not null) type=MyISAM;
create table starship_pilots (starships_id bigint not null, pilots_id bigint not null) type=MyISAM;
create table vehicle (id bigint not null auto_increment, cost_in_credits varchar(255), crew varchar(255), length varchar(255), manufacturer varchar(255), max_atmosphering_speed varchar(255), model varchar(255), name varchar(255), passengers varchar(255), vehicle_class varchar(255), primary key (id)) type=MyISAM;
create table vehicle_films (vehicles_id bigint not null, films_id bigint not null) type=MyISAM;
create table vehicle_pilots (vehicles_id bigint not null, pilots_id bigint not null) type=MyISAM;
alter table person add constraint FK9xoqlm4cvgwol95469rqtauq4 foreign key (homeworld_id) references planet (id);
alter table person_films add constraint FK6v1bygbdvv02v072nh0mxkqpn foreign key (films_id) references film (id);
alter table person_films add constraint FKavfmyayv2v0yutn7qnh2o7wkm foreign key (characters_id) references person (id);
alter table planet_films add constraint FKj6xfpgdqqmb34j880l60nsfcw foreign key (films_id) references film (id);
alter table planet_films add constraint FKb7b8v6em5vxkmigjqqk3kxctv foreign key (planets_id) references planet (id);
alter table planet_residents add constraint FKhashmp7rcgqdvrbecjsh09m5r foreign key (residents_id) references person (id);
alter table planet_residents add constraint FK7j18qhysxpxcqtujirava927t foreign key (planet_id) references planet (id);
alter table species add constraint FKp61wjv50m3nfvoke36v174sn5 foreign key (homeworld_id) references planet (id);
alter table species_films add constraint FK2t8l5jefsmxfxsxy49poro10v foreign key (films_id) references film (id);
alter table species_films add constraint FKi5t8kxgr865bol115vhpcrsb8 foreign key (species_id) references species (id);
alter table species_people add constraint FK5uaqwr63ov7wd1an62sukw908 foreign key (people_id) references person (id);
alter table species_people add constraint FK7soq9pv3s6djgtxmb7431fgee foreign key (species_id) references species (id);
alter table starship_films add constraint FKpnmpsm2g9bir1km1nufbaor4i foreign key (films_id) references film (id);
alter table starship_films add constraint FKjmrtlhumxa8gkjt3ufjvr5u0c foreign key (starships_id) references starship (id);
alter table starship_pilots add constraint FKmg96tf6y6o5aqaucqj38ep9fl foreign key (pilots_id) references person (id);
alter table starship_pilots add constraint FKj8woi4aqnwlx2tay4w7saq83y foreign key (starships_id) references starship (id);
alter table vehicle_films add constraint FKs8cfkhvkn8cv4yaxbm1u1rih7 foreign key (films_id) references film (id);
alter table vehicle_films add constraint FKfl30g9l5ocqbg7p3k9w5v25fb foreign key (vehicles_id) references vehicle (id);
alter table vehicle_pilots add constraint FKqimn856lkidkyajfbi4mm3xvy foreign key (pilots_id) references person (id);
alter table vehicle_pilots add constraint FKep6tpw2kgcwsnlkr1pb4qqq16 foreign key (vehicles_id) references vehicle (id);
create table film (id bigint not null auto_increment, director varchar(255), episode_id integer not null, producer varchar(255), release_date datetime, title varchar(255), primary key (id)) type=MyISAM;
create table person (id bigint not null auto_increment, birth_year varchar(255), gender varchar(255), height varchar(255), mass varchar(255), name varchar(255), skin_color varchar(255), homeworld_id bigint, primary key (id)) type=MyISAM;
create table person_films (characters_id bigint not null, films_id bigint not null) type=MyISAM;
create table planet (id bigint not null auto_increment, climate varchar(255), diameter varchar(255), gravity varchar(255), name varchar(255), orbital_period varchar(255), population varchar(255), rotation_period varchar(255), surface_water varchar(255), terrain varchar(255), primary key (id)) type=MyISAM;
create table planet_films (planets_id bigint not null, films_id bigint not null) type=MyISAM;
create table planet_residents (planet_id bigint not null, residents_id bigint not null) type=MyISAM;
create table species (id bigint not null auto_increment, avg_height varchar(255), avg_lifespan varchar(255), classification varchar(255), designation varchar(255), eye_colors varchar(255), language varchar(255), name varchar(255), skin_colors varchar(255), homeworld_id bigint, primary key (id)) type=MyISAM;
create table species_films (species_id bigint not null, films_id bigint not null) type=MyISAM;
create table species_people (species_id bigint not null, people_id bigint not null) type=MyISAM;
create table starship (id bigint not null auto_increment, cost_in_credits varchar(255), crew varchar(255), length varchar(255), manufacturer varchar(255), max_atmosphering_speed varchar(255), max_megalights varchar(255), model varchar(255), name varchar(255), passengers varchar(255), starship_class varchar(255), primary key (id)) type=MyISAM;
create table starship_films (starships_id bigint not null, films_id bigint not null) type=MyISAM;
create table starship_pilots (starships_id bigint not null, pilots_id bigint not null) type=MyISAM;
create table vehicle (id bigint not null auto_increment, cost_in_credits varchar(255), crew varchar(255), length varchar(255), manufacturer varchar(255), max_atmosphering_speed varchar(255), model varchar(255), name varchar(255), passengers varchar(255), vehicle_class varchar(255), primary key (id)) type=MyISAM;
create table vehicle_films (vehicles_id bigint not null, films_id bigint not null) type=MyISAM;
create table vehicle_pilots (vehicles_id bigint not null, pilots_id bigint not null) type=MyISAM;
alter table person add constraint FK9xoqlm4cvgwol95469rqtauq4 foreign key (homeworld_id) references planet (id);
alter table person_films add constraint FK6v1bygbdvv02v072nh0mxkqpn foreign key (films_id) references film (id);
alter table person_films add constraint FKavfmyayv2v0yutn7qnh2o7wkm foreign key (characters_id) references person (id);
alter table planet_films add constraint FKj6xfpgdqqmb34j880l60nsfcw foreign key (films_id) references film (id);
alter table planet_films add constraint FKb7b8v6em5vxkmigjqqk3kxctv foreign key (planets_id) references planet (id);
alter table planet_residents add constraint FKhashmp7rcgqdvrbecjsh09m5r foreign key (residents_id) references person (id);
alter table planet_residents add constraint FK7j18qhysxpxcqtujirava927t foreign key (planet_id) references planet (id);
alter table species add constraint FKp61wjv50m3nfvoke36v174sn5 foreign key (homeworld_id) references planet (id);
alter table species_films add constraint FK2t8l5jefsmxfxsxy49poro10v foreign key (films_id) references film (id);
alter table species_films add constraint FKi5t8kxgr865bol115vhpcrsb8 foreign key (species_id) references species (id);
alter table species_people add constraint FK5uaqwr63ov7wd1an62sukw908 foreign key (people_id) references person (id);
alter table species_people add constraint FK7soq9pv3s6djgtxmb7431fgee foreign key (species_id) references species (id);
alter table starship_films add constraint FKpnmpsm2g9bir1km1nufbaor4i foreign key (films_id) references film (id);
alter table starship_films add constraint FKjmrtlhumxa8gkjt3ufjvr5u0c foreign key (starships_id) references starship (id);
alter table starship_pilots add constraint FKmg96tf6y6o5aqaucqj38ep9fl foreign key (pilots_id) references person (id);
alter table starship_pilots add constraint FKj8woi4aqnwlx2tay4w7saq83y foreign key (starships_id) references starship (id);
alter table vehicle_films add constraint FKs8cfkhvkn8cv4yaxbm1u1rih7 foreign key (films_id) references film (id);
alter table vehicle_films add constraint FKfl30g9l5ocqbg7p3k9w5v25fb foreign key (vehicles_id) references vehicle (id);
alter table vehicle_pilots add constraint FKqimn856lkidkyajfbi4mm3xvy foreign key (pilots_id) references person (id);
alter table vehicle_pilots add constraint FKep6tpw2kgcwsnlkr1pb4qqq16 foreign key (vehicles_id) references vehicle (id);
create table film (id bigint not null auto_increment, director varchar(255), episode_id integer not null, producer varchar(255), release_date datetime, title varchar(255), primary key (id)) type=MyISAM;
create table person (id bigint not null auto_increment, birth_year varchar(255), gender varchar(255), height varchar(255), mass varchar(255), name varchar(255), skin_color varchar(255), homeworld_id bigint, primary key (id)) type=MyISAM;
create table person_films (characters_id bigint not null, films_id bigint not null) type=MyISAM;
create table planet (id bigint not null auto_increment, climate varchar(255), diameter varchar(255), gravity varchar(255), name varchar(255), orbital_period varchar(255), population varchar(255), rotation_period varchar(255), surface_water varchar(255), terrain varchar(255), primary key (id)) type=MyISAM;
create table planet_films (planets_id bigint not null, films_id bigint not null) type=MyISAM;
create table planet_residents (planet_id bigint not null, residents_id bigint not null) type=MyISAM;
create table species (id bigint not null auto_increment, avg_height varchar(255), avg_lifespan varchar(255), classification varchar(255), designation varchar(255), eye_colors varchar(255), language varchar(255), name varchar(255), skin_colors varchar(255), homeworld_id bigint, primary key (id)) type=MyISAM;
create table species_films (species_id bigint not null, films_id bigint not null) type=MyISAM;
create table species_people (species_id bigint not null, people_id bigint not null) type=MyISAM;
create table starship (id bigint not null auto_increment, cost_in_credits varchar(255), crew varchar(255), length varchar(255), manufacturer varchar(255), max_atmosphering_speed varchar(255), max_megalights varchar(255), model varchar(255), name varchar(255), passengers varchar(255), starship_class varchar(255), primary key (id)) type=MyISAM;
create table starship_films (starships_id bigint not null, films_id bigint not null) type=MyISAM;
create table starship_pilots (starships_id bigint not null, pilots_id bigint not null) type=MyISAM;
create table vehicle (id bigint not null auto_increment, cost_in_credits varchar(255), crew varchar(255), length varchar(255), manufacturer varchar(255), max_atmosphering_speed varchar(255), model varchar(255), name varchar(255), passengers varchar(255), vehicle_class varchar(255), primary key (id)) type=MyISAM;
create table vehicle_films (vehicles_id bigint not null, films_id bigint not null) type=MyISAM;
create table vehicle_pilots (vehicles_id bigint not null, pilots_id bigint not null) type=MyISAM;
alter table person add constraint FK9xoqlm4cvgwol95469rqtauq4 foreign key (homeworld_id) references planet (id);
alter table person_films add constraint FK6v1bygbdvv02v072nh0mxkqpn foreign key (films_id) references film (id);
alter table person_films add constraint FKavfmyayv2v0yutn7qnh2o7wkm foreign key (characters_id) references person (id);
alter table planet_films add constraint FKj6xfpgdqqmb34j880l60nsfcw foreign key (films_id) references film (id);
alter table planet_films add constraint FKb7b8v6em5vxkmigjqqk3kxctv foreign key (planets_id) references planet (id);
alter table planet_residents add constraint FKhashmp7rcgqdvrbecjsh09m5r foreign key (residents_id) references person (id);
alter table planet_residents add constraint FK7j18qhysxpxcqtujirava927t foreign key (planet_id) references planet (id);
alter table species add constraint FKp61wjv50m3nfvoke36v174sn5 foreign key (homeworld_id) references planet (id);
alter table species_films add constraint FK2t8l5jefsmxfxsxy49poro10v foreign key (films_id) references film (id);
alter table species_films add constraint FKi5t8kxgr865bol115vhpcrsb8 foreign key (species_id) references species (id);
alter table species_people add constraint FK5uaqwr63ov7wd1an62sukw908 foreign key (people_id) references person (id);
alter table species_people add constraint FK7soq9pv3s6djgtxmb7431fgee foreign key (species_id) references species (id);
alter table starship_films add constraint FKpnmpsm2g9bir1km1nufbaor4i foreign key (films_id) references film (id);
alter table starship_films add constraint FKjmrtlhumxa8gkjt3ufjvr5u0c foreign key (starships_id) references starship (id);
alter table starship_pilots add constraint FKmg96tf6y6o5aqaucqj38ep9fl foreign key (pilots_id) references person (id);
alter table starship_pilots add constraint FKj8woi4aqnwlx2tay4w7saq83y foreign key (starships_id) references starship (id);
alter table vehicle_films add constraint FKs8cfkhvkn8cv4yaxbm1u1rih7 foreign key (films_id) references film (id);
alter table vehicle_films add constraint FKfl30g9l5ocqbg7p3k9w5v25fb foreign key (vehicles_id) references vehicle (id);
alter table vehicle_pilots add constraint FKqimn856lkidkyajfbi4mm3xvy foreign key (pilots_id) references person (id);
alter table vehicle_pilots add constraint FKep6tpw2kgcwsnlkr1pb4qqq16 foreign key (vehicles_id) references vehicle (id);
create table film (id bigint not null auto_increment, director varchar(255), episode_id integer not null, producer varchar(255), release_date datetime, title varchar(255), primary key (id)) type=MyISAM;
create table person (id bigint not null auto_increment, birth_year varchar(255), gender varchar(255), height varchar(255), mass varchar(255), name varchar(255), skin_color varchar(255), homeworld_id bigint, primary key (id)) type=MyISAM;
create table person_films (characters_id bigint not null, films_id bigint not null) type=MyISAM;
create table planet (id bigint not null auto_increment, climate varchar(255), diameter varchar(255), gravity varchar(255), name varchar(255), orbital_period varchar(255), population varchar(255), rotation_period varchar(255), surface_water varchar(255), terrain varchar(255), primary key (id)) type=MyISAM;
create table planet_films (planets_id bigint not null, films_id bigint not null) type=MyISAM;
create table planet_residents (planet_id bigint not null, residents_id bigint not null) type=MyISAM;
create table species (id bigint not null auto_increment, avg_height varchar(255), avg_lifespan varchar(255), classification varchar(255), designation varchar(255), eye_colors varchar(255), language varchar(255), name varchar(255), skin_colors varchar(255), homeworld_id bigint, primary key (id)) type=MyISAM;
create table species_films (species_id bigint not null, films_id bigint not null) type=MyISAM;
create table species_people (species_id bigint not null, people_id bigint not null) type=MyISAM;
create table starship (id bigint not null auto_increment, cost_in_credits varchar(255), crew varchar(255), length varchar(255), manufacturer varchar(255), max_atmosphering_speed varchar(255), max_megalights varchar(255), model varchar(255), name varchar(255), passengers varchar(255), starship_class varchar(255), primary key (id)) type=MyISAM;
create table starship_films (starships_id bigint not null, films_id bigint not null) type=MyISAM;
create table starship_pilots (starships_id bigint not null, pilots_id bigint not null) type=MyISAM;
create table vehicle (id bigint not null auto_increment, cost_in_credits varchar(255), crew varchar(255), length varchar(255), manufacturer varchar(255), max_atmosphering_speed varchar(255), model varchar(255), name varchar(255), passengers varchar(255), vehicle_class varchar(255), primary key (id)) type=MyISAM;
create table vehicle_films (vehicles_id bigint not null, films_id bigint not null) type=MyISAM;
create table vehicle_pilots (vehicles_id bigint not null, pilots_id bigint not null) type=MyISAM;
alter table person add constraint FK9xoqlm4cvgwol95469rqtauq4 foreign key (homeworld_id) references planet (id);
alter table person_films add constraint FK6v1bygbdvv02v072nh0mxkqpn foreign key (films_id) references film (id);
alter table person_films add constraint FKavfmyayv2v0yutn7qnh2o7wkm foreign key (characters_id) references person (id);
alter table planet_films add constraint FKj6xfpgdqqmb34j880l60nsfcw foreign key (films_id) references film (id);
alter table planet_films add constraint FKb7b8v6em5vxkmigjqqk3kxctv foreign key (planets_id) references planet (id);
alter table planet_residents add constraint FKhashmp7rcgqdvrbecjsh09m5r foreign key (residents_id) references person (id);
alter table planet_residents add constraint FK7j18qhysxpxcqtujirava927t foreign key (planet_id) references planet (id);
alter table species add constraint FKp61wjv50m3nfvoke36v174sn5 foreign key (homeworld_id) references planet (id);
alter table species_films add constraint FK2t8l5jefsmxfxsxy49poro10v foreign key (films_id) references film (id);
alter table species_films add constraint FKi5t8kxgr865bol115vhpcrsb8 foreign key (species_id) references species (id);
alter table species_people add constraint FK5uaqwr63ov7wd1an62sukw908 foreign key (people_id) references person (id);
alter table species_people add constraint FK7soq9pv3s6djgtxmb7431fgee foreign key (species_id) references species (id);
alter table starship_films add constraint FKpnmpsm2g9bir1km1nufbaor4i foreign key (films_id) references film (id);
alter table starship_films add constraint FKjmrtlhumxa8gkjt3ufjvr5u0c foreign key (starships_id) references starship (id);
alter table starship_pilots add constraint FKmg96tf6y6o5aqaucqj38ep9fl foreign key (pilots_id) references person (id);
alter table starship_pilots add constraint FKj8woi4aqnwlx2tay4w7saq83y foreign key (starships_id) references starship (id);
alter table vehicle_films add constraint FKs8cfkhvkn8cv4yaxbm1u1rih7 foreign key (films_id) references film (id);
alter table vehicle_films add constraint FKfl30g9l5ocqbg7p3k9w5v25fb foreign key (vehicles_id) references vehicle (id);
alter table vehicle_pilots add constraint FKqimn856lkidkyajfbi4mm3xvy foreign key (pilots_id) references person (id);
alter table vehicle_pilots add constraint FKep6tpw2kgcwsnlkr1pb4qqq16 foreign key (vehicles_id) references vehicle (id);
create table film (id bigint not null auto_increment, director varchar(255), episode_id integer not null, producer varchar(255), release_date datetime, title varchar(255), primary key (id)) type=MyISAM;
create table person (id bigint not null auto_increment, birth_year varchar(255), gender varchar(255), height varchar(255), mass varchar(255), name varchar(255), skin_color varchar(255), homeworld_id bigint, primary key (id)) type=MyISAM;
create table person_films (characters_id bigint not null, films_id bigint not null) type=MyISAM;
create table planet (id bigint not null auto_increment, climate varchar(255), diameter varchar(255), gravity varchar(255), name varchar(255), orbital_period varchar(255), population varchar(255), rotation_period varchar(255), surface_water varchar(255), terrain varchar(255), primary key (id)) type=MyISAM;
create table planet_films (planets_id bigint not null, films_id bigint not null) type=MyISAM;
create table planet_residents (planet_id bigint not null, residents_id bigint not null) type=MyISAM;
create table species (id bigint not null auto_increment, avg_height varchar(255), avg_lifespan varchar(255), classification varchar(255), designation varchar(255), eye_colors varchar(255), language varchar(255), name varchar(255), skin_colors varchar(255), homeworld_id bigint, primary key (id)) type=MyISAM;
create table species_films (species_id bigint not null, films_id bigint not null) type=MyISAM;
create table species_people (species_id bigint not null, people_id bigint not null) type=MyISAM;
create table starship (id bigint not null auto_increment, cost_in_credits varchar(255), crew varchar(255), length varchar(255), manufacturer varchar(255), max_atmosphering_speed varchar(255), max_megalights varchar(255), model varchar(255), name varchar(255), passengers varchar(255), starship_class varchar(255), primary key (id)) type=MyISAM;
create table starship_films (starships_id bigint not null, films_id bigint not null) type=MyISAM;
create table starship_pilots (starships_id bigint not null, pilots_id bigint not null) type=MyISAM;
create table vehicle (id bigint not null auto_increment, cost_in_credits varchar(255), crew varchar(255), length varchar(255), manufacturer varchar(255), max_atmosphering_speed varchar(255), model varchar(255), name varchar(255), passengers varchar(255), vehicle_class varchar(255), primary key (id)) type=MyISAM;
create table vehicle_films (vehicles_id bigint not null, films_id bigint not null) type=MyISAM;
create table vehicle_pilots (vehicles_id bigint not null, pilots_id bigint not null) type=MyISAM;
alter table person add constraint FK9xoqlm4cvgwol95469rqtauq4 foreign key (homeworld_id) references planet (id);
alter table person_films add constraint FK6v1bygbdvv02v072nh0mxkqpn foreign key (films_id) references film (id);
alter table person_films add constraint FKavfmyayv2v0yutn7qnh2o7wkm foreign key (characters_id) references person (id);
alter table planet_films add constraint FKj6xfpgdqqmb34j880l60nsfcw foreign key (films_id) references film (id);
alter table planet_films add constraint FKb7b8v6em5vxkmigjqqk3kxctv foreign key (planets_id) references planet (id);
alter table planet_residents add constraint FKhashmp7rcgqdvrbecjsh09m5r foreign key (residents_id) references person (id);
alter table planet_residents add constraint FK7j18qhysxpxcqtujirava927t foreign key (planet_id) references planet (id);
alter table species add constraint FKp61wjv50m3nfvoke36v174sn5 foreign key (homeworld_id) references planet (id);
alter table species_films add constraint FK2t8l5jefsmxfxsxy49poro10v foreign key (films_id) references film (id);
alter table species_films add constraint FKi5t8kxgr865bol115vhpcrsb8 foreign key (species_id) references species (id);
alter table species_people add constraint FK5uaqwr63ov7wd1an62sukw908 foreign key (people_id) references person (id);
alter table species_people add constraint FK7soq9pv3s6djgtxmb7431fgee foreign key (species_id) references species (id);
alter table starship_films add constraint FKpnmpsm2g9bir1km1nufbaor4i foreign key (films_id) references film (id);
alter table starship_films add constraint FKjmrtlhumxa8gkjt3ufjvr5u0c foreign key (starships_id) references starship (id);
alter table starship_pilots add constraint FKmg96tf6y6o5aqaucqj38ep9fl foreign key (pilots_id) references person (id);
alter table starship_pilots add constraint FKj8woi4aqnwlx2tay4w7saq83y foreign key (starships_id) references starship (id);
alter table vehicle_films add constraint FKs8cfkhvkn8cv4yaxbm1u1rih7 foreign key (films_id) references film (id);
alter table vehicle_films add constraint FKfl30g9l5ocqbg7p3k9w5v25fb foreign key (vehicles_id) references vehicle (id);
alter table vehicle_pilots add constraint FKqimn856lkidkyajfbi4mm3xvy foreign key (pilots_id) references person (id);
alter table vehicle_pilots add constraint FKep6tpw2kgcwsnlkr1pb4qqq16 foreign key (vehicles_id) references vehicle (id);
create table film (id bigint not null auto_increment, director varchar(255), episode_id integer not null, producer varchar(255), release_date datetime, title varchar(255), primary key (id)) type=MyISAM;
create table person (id bigint not null auto_increment, birth_year varchar(255), gender varchar(255), height varchar(255), mass varchar(255), name varchar(255), skin_color varchar(255), homeworld_id bigint, primary key (id)) type=MyISAM;
create table person_films (characters_id bigint not null, films_id bigint not null) type=MyISAM;
create table planet (id bigint not null auto_increment, climate varchar(255), diameter varchar(255), gravity varchar(255), name varchar(255), orbital_period varchar(255), population varchar(255), rotation_period varchar(255), surface_water varchar(255), terrain varchar(255), primary key (id)) type=MyISAM;
create table planet_films (planets_id bigint not null, films_id bigint not null) type=MyISAM;
create table planet_residents (planet_id bigint not null, residents_id bigint not null) type=MyISAM;
create table species (id bigint not null auto_increment, avg_height varchar(255), avg_lifespan varchar(255), classification varchar(255), designation varchar(255), eye_colors varchar(255), language varchar(255), name varchar(255), skin_colors varchar(255), homeworld_id bigint, primary key (id)) type=MyISAM;
create table species_films (species_id bigint not null, films_id bigint not null) type=MyISAM;
create table species_people (species_id bigint not null, people_id bigint not null) type=MyISAM;
create table starship (id bigint not null auto_increment, cost_in_credits varchar(255), crew varchar(255), length varchar(255), manufacturer varchar(255), max_atmosphering_speed varchar(255), max_megalights varchar(255), model varchar(255), name varchar(255), passengers varchar(255), starship_class varchar(255), primary key (id)) type=MyISAM;
create table starship_films (starships_id bigint not null, films_id bigint not null) type=MyISAM;
create table starship_pilots (starships_id bigint not null, pilots_id bigint not null) type=MyISAM;
create table vehicle (id bigint not null auto_increment, cost_in_credits varchar(255), crew varchar(255), length varchar(255), manufacturer varchar(255), max_atmosphering_speed varchar(255), model varchar(255), name varchar(255), passengers varchar(255), vehicle_class varchar(255), primary key (id)) type=MyISAM;
create table vehicle_films (vehicles_id bigint not null, films_id bigint not null) type=MyISAM;
create table vehicle_pilots (vehicles_id bigint not null, pilots_id bigint not null) type=MyISAM;
alter table person add constraint FK9xoqlm4cvgwol95469rqtauq4 foreign key (homeworld_id) references planet (id);
alter table person_films add constraint FK6v1bygbdvv02v072nh0mxkqpn foreign key (films_id) references film (id);
alter table person_films add constraint FKavfmyayv2v0yutn7qnh2o7wkm foreign key (characters_id) references person (id);
alter table planet_films add constraint FKj6xfpgdqqmb34j880l60nsfcw foreign key (films_id) references film (id);
alter table planet_films add constraint FKb7b8v6em5vxkmigjqqk3kxctv foreign key (planets_id) references planet (id);
alter table planet_residents add constraint FKhashmp7rcgqdvrbecjsh09m5r foreign key (residents_id) references person (id);
alter table planet_residents add constraint FK7j18qhysxpxcqtujirava927t foreign key (planet_id) references planet (id);
alter table species add constraint FKp61wjv50m3nfvoke36v174sn5 foreign key (homeworld_id) references planet (id);
alter table species_films add constraint FK2t8l5jefsmxfxsxy49poro10v foreign key (films_id) references film (id);
alter table species_films add constraint FKi5t8kxgr865bol115vhpcrsb8 foreign key (species_id) references species (id);
alter table species_people add constraint FK5uaqwr63ov7wd1an62sukw908 foreign key (people_id) references person (id);
alter table species_people add constraint FK7soq9pv3s6djgtxmb7431fgee foreign key (species_id) references species (id);
alter table starship_films add constraint FKpnmpsm2g9bir1km1nufbaor4i foreign key (films_id) references film (id);
alter table starship_films add constraint FKjmrtlhumxa8gkjt3ufjvr5u0c foreign key (starships_id) references starship (id);
alter table starship_pilots add constraint FKmg96tf6y6o5aqaucqj38ep9fl foreign key (pilots_id) references person (id);
alter table starship_pilots add constraint FKj8woi4aqnwlx2tay4w7saq83y foreign key (starships_id) references starship (id);
alter table vehicle_films add constraint FKs8cfkhvkn8cv4yaxbm1u1rih7 foreign key (films_id) references film (id);
alter table vehicle_films add constraint FKfl30g9l5ocqbg7p3k9w5v25fb foreign key (vehicles_id) references vehicle (id);
alter table vehicle_pilots add constraint FKqimn856lkidkyajfbi4mm3xvy foreign key (pilots_id) references person (id);
alter table vehicle_pilots add constraint FKep6tpw2kgcwsnlkr1pb4qqq16 foreign key (vehicles_id) references vehicle (id);
create table film (id bigint not null auto_increment, director varchar(255), episode_id integer not null, producer varchar(255), release_date datetime, title varchar(255), primary key (id)) type=MyISAM;
create table person (id bigint not null auto_increment, birth_year varchar(255), gender varchar(255), height varchar(255), mass varchar(255), name varchar(255), skin_color varchar(255), homeworld_id bigint, primary key (id)) type=MyISAM;
create table person_films (characters_id bigint not null, films_id bigint not null) type=MyISAM;
create table planet (id bigint not null auto_increment, climate varchar(255), diameter varchar(255), gravity varchar(255), name varchar(255), orbital_period varchar(255), population varchar(255), rotation_period varchar(255), surface_water varchar(255), terrain varchar(255), primary key (id)) type=MyISAM;
create table planet_films (planets_id bigint not null, films_id bigint not null) type=MyISAM;
create table planet_residents (planet_id bigint not null, residents_id bigint not null) type=MyISAM;
create table species (id bigint not null auto_increment, avg_height varchar(255), avg_lifespan varchar(255), classification varchar(255), designation varchar(255), eye_colors varchar(255), language varchar(255), name varchar(255), skin_colors varchar(255), homeworld_id bigint, primary key (id)) type=MyISAM;
create table species_films (species_id bigint not null, films_id bigint not null) type=MyISAM;
create table species_people (species_id bigint not null, people_id bigint not null) type=MyISAM;
create table starship (id bigint not null auto_increment, cost_in_credits varchar(255), crew varchar(255), length varchar(255), manufacturer varchar(255), max_atmosphering_speed varchar(255), max_megalights varchar(255), model varchar(255), name varchar(255), passengers varchar(255), starship_class varchar(255), primary key (id)) type=MyISAM;
create table starship_films (starships_id bigint not null, films_id bigint not null) type=MyISAM;
create table starship_pilots (starships_id bigint not null, pilots_id bigint not null) type=MyISAM;
create table vehicle (id bigint not null auto_increment, cost_in_credits varchar(255), crew varchar(255), length varchar(255), manufacturer varchar(255), max_atmosphering_speed varchar(255), model varchar(255), name varchar(255), passengers varchar(255), vehicle_class varchar(255), primary key (id)) type=MyISAM;
create table vehicle_films (vehicles_id bigint not null, films_id bigint not null) type=MyISAM;
create table vehicle_pilots (vehicles_id bigint not null, pilots_id bigint not null) type=MyISAM;
alter table person add constraint FK9xoqlm4cvgwol95469rqtauq4 foreign key (homeworld_id) references planet (id);
alter table person_films add constraint FK6v1bygbdvv02v072nh0mxkqpn foreign key (films_id) references film (id);
alter table person_films add constraint FKavfmyayv2v0yutn7qnh2o7wkm foreign key (characters_id) references person (id);
alter table planet_films add constraint FKj6xfpgdqqmb34j880l60nsfcw foreign key (films_id) references film (id);
alter table planet_films add constraint FKb7b8v6em5vxkmigjqqk3kxctv foreign key (planets_id) references planet (id);
alter table planet_residents add constraint FKhashmp7rcgqdvrbecjsh09m5r foreign key (residents_id) references person (id);
alter table planet_residents add constraint FK7j18qhysxpxcqtujirava927t foreign key (planet_id) references planet (id);
alter table species add constraint FKp61wjv50m3nfvoke36v174sn5 foreign key (homeworld_id) references planet (id);
alter table species_films add constraint FK2t8l5jefsmxfxsxy49poro10v foreign key (films_id) references film (id);
alter table species_films add constraint FKi5t8kxgr865bol115vhpcrsb8 foreign key (species_id) references species (id);
alter table species_people add constraint FK5uaqwr63ov7wd1an62sukw908 foreign key (people_id) references person (id);
alter table species_people add constraint FK7soq9pv3s6djgtxmb7431fgee foreign key (species_id) references species (id);
alter table starship_films add constraint FKpnmpsm2g9bir1km1nufbaor4i foreign key (films_id) references film (id);
alter table starship_films add constraint FKjmrtlhumxa8gkjt3ufjvr5u0c foreign key (starships_id) references starship (id);
alter table starship_pilots add constraint FKmg96tf6y6o5aqaucqj38ep9fl foreign key (pilots_id) references person (id);
alter table starship_pilots add constraint FKj8woi4aqnwlx2tay4w7saq83y foreign key (starships_id) references starship (id);
alter table vehicle_films add constraint FKs8cfkhvkn8cv4yaxbm1u1rih7 foreign key (films_id) references film (id);
alter table vehicle_films add constraint FKfl30g9l5ocqbg7p3k9w5v25fb foreign key (vehicles_id) references vehicle (id);
alter table vehicle_pilots add constraint FKqimn856lkidkyajfbi4mm3xvy foreign key (pilots_id) references person (id);
alter table vehicle_pilots add constraint FKep6tpw2kgcwsnlkr1pb4qqq16 foreign key (vehicles_id) references vehicle (id);
create table film (id bigint not null auto_increment, director varchar(255), episode_id integer not null, producer varchar(255), release_date datetime, title varchar(255), primary key (id)) type=MyISAM;
create table person (id bigint not null auto_increment, birth_year varchar(255), gender varchar(255), height varchar(255), mass varchar(255), name varchar(255), skin_color varchar(255), homeworld_id bigint, primary key (id)) type=MyISAM;
create table person_films (characters_id bigint not null, films_id bigint not null) type=MyISAM;
create table planet (id bigint not null auto_increment, climate varchar(255), diameter varchar(255), gravity varchar(255), name varchar(255), orbital_period varchar(255), population varchar(255), rotation_period varchar(255), surface_water varchar(255), terrain varchar(255), primary key (id)) type=MyISAM;
create table planet_films (planets_id bigint not null, films_id bigint not null) type=MyISAM;
create table planet_residents (planet_id bigint not null, residents_id bigint not null) type=MyISAM;
create table species (id bigint not null auto_increment, avg_height varchar(255), avg_lifespan varchar(255), classification varchar(255), designation varchar(255), eye_colors varchar(255), language varchar(255), name varchar(255), skin_colors varchar(255), homeworld_id bigint, primary key (id)) type=MyISAM;
create table species_films (species_id bigint not null, films_id bigint not null) type=MyISAM;
create table species_people (species_id bigint not null, people_id bigint not null) type=MyISAM;
create table starship (id bigint not null auto_increment, cost_in_credits varchar(255), crew varchar(255), length varchar(255), manufacturer varchar(255), max_atmosphering_speed varchar(255), max_megalights varchar(255), model varchar(255), name varchar(255), passengers varchar(255), starship_class varchar(255), primary key (id)) type=MyISAM;
create table starship_films (starships_id bigint not null, films_id bigint not null) type=MyISAM;
create table starship_pilots (starships_id bigint not null, pilots_id bigint not null) type=MyISAM;
create table vehicle (id bigint not null auto_increment, cost_in_credits varchar(255), crew varchar(255), length varchar(255), manufacturer varchar(255), max_atmosphering_speed varchar(255), model varchar(255), name varchar(255), passengers varchar(255), vehicle_class varchar(255), primary key (id)) type=MyISAM;
create table vehicle_films (vehicles_id bigint not null, films_id bigint not null) type=MyISAM;
create table vehicle_pilots (vehicles_id bigint not null, pilots_id bigint not null) type=MyISAM;
alter table person add constraint FK9xoqlm4cvgwol95469rqtauq4 foreign key (homeworld_id) references planet (id);
alter table person_films add constraint FK6v1bygbdvv02v072nh0mxkqpn foreign key (films_id) references film (id);
alter table person_films add constraint FKavfmyayv2v0yutn7qnh2o7wkm foreign key (characters_id) references person (id);
alter table planet_films add constraint FKj6xfpgdqqmb34j880l60nsfcw foreign key (films_id) references film (id);
alter table planet_films add constraint FKb7b8v6em5vxkmigjqqk3kxctv foreign key (planets_id) references planet (id);
alter table planet_residents add constraint FKhashmp7rcgqdvrbecjsh09m5r foreign key (residents_id) references person (id);
alter table planet_residents add constraint FK7j18qhysxpxcqtujirava927t foreign key (planet_id) references planet (id);
alter table species add constraint FKp61wjv50m3nfvoke36v174sn5 foreign key (homeworld_id) references planet (id);
alter table species_films add constraint FK2t8l5jefsmxfxsxy49poro10v foreign key (films_id) references film (id);
alter table species_films add constraint FKi5t8kxgr865bol115vhpcrsb8 foreign key (species_id) references species (id);
alter table species_people add constraint FK5uaqwr63ov7wd1an62sukw908 foreign key (people_id) references person (id);
alter table species_people add constraint FK7soq9pv3s6djgtxmb7431fgee foreign key (species_id) references species (id);
alter table starship_films add constraint FKpnmpsm2g9bir1km1nufbaor4i foreign key (films_id) references film (id);
alter table starship_films add constraint FKjmrtlhumxa8gkjt3ufjvr5u0c foreign key (starships_id) references starship (id);
alter table starship_pilots add constraint FKmg96tf6y6o5aqaucqj38ep9fl foreign key (pilots_id) references person (id);
alter table starship_pilots add constraint FKj8woi4aqnwlx2tay4w7saq83y foreign key (starships_id) references starship (id);
alter table vehicle_films add constraint FKs8cfkhvkn8cv4yaxbm1u1rih7 foreign key (films_id) references film (id);
alter table vehicle_films add constraint FKfl30g9l5ocqbg7p3k9w5v25fb foreign key (vehicles_id) references vehicle (id);
alter table vehicle_pilots add constraint FKqimn856lkidkyajfbi4mm3xvy foreign key (pilots_id) references person (id);
alter table vehicle_pilots add constraint FKep6tpw2kgcwsnlkr1pb4qqq16 foreign key (vehicles_id) references vehicle (id);
create table film (id bigint not null auto_increment, director varchar(255), episode_id integer not null, producer varchar(255), release_date datetime, title varchar(255), primary key (id)) type=MyISAM;
create table person (id bigint not null auto_increment, birth_year varchar(255), gender varchar(255), height varchar(255), mass varchar(255), name varchar(255), skin_color varchar(255), homeworld_id bigint, primary key (id)) type=MyISAM;
create table person_films (characters_id bigint not null, films_id bigint not null) type=MyISAM;
create table planet (id bigint not null auto_increment, climate varchar(255), diameter varchar(255), gravity varchar(255), name varchar(255), orbital_period varchar(255), population varchar(255), rotation_period varchar(255), surface_water varchar(255), terrain varchar(255), primary key (id)) type=MyISAM;
create table planet_films (planets_id bigint not null, films_id bigint not null) type=MyISAM;
create table planet_residents (planet_id bigint not null, residents_id bigint not null) type=MyISAM;
create table species (id bigint not null auto_increment, avg_height varchar(255), avg_lifespan varchar(255), classification varchar(255), designation varchar(255), eye_colors varchar(255), language varchar(255), name varchar(255), skin_colors varchar(255), homeworld_id bigint, primary key (id)) type=MyISAM;
create table species_films (species_id bigint not null, films_id bigint not null) type=MyISAM;
create table species_people (species_id bigint not null, people_id bigint not null) type=MyISAM;
create table starship (id bigint not null auto_increment, cost_in_credits varchar(255), crew varchar(255), length varchar(255), manufacturer varchar(255), max_atmosphering_speed varchar(255), max_megalights varchar(255), model varchar(255), name varchar(255), passengers varchar(255), starship_class varchar(255), primary key (id)) type=MyISAM;
create table starship_films (starships_id bigint not null, films_id bigint not null) type=MyISAM;
create table starship_pilots (starships_id bigint not null, pilots_id bigint not null) type=MyISAM;
create table vehicle (id bigint not null auto_increment, cost_in_credits varchar(255), crew varchar(255), length varchar(255), manufacturer varchar(255), max_atmosphering_speed varchar(255), model varchar(255), name varchar(255), passengers varchar(255), vehicle_class varchar(255), primary key (id)) type=MyISAM;
create table vehicle_films (vehicles_id bigint not null, films_id bigint not null) type=MyISAM;
create table vehicle_pilots (vehicles_id bigint not null, pilots_id bigint not null) type=MyISAM;
alter table person add constraint FK9xoqlm4cvgwol95469rqtauq4 foreign key (homeworld_id) references planet (id);
alter table person_films add constraint FK6v1bygbdvv02v072nh0mxkqpn foreign key (films_id) references film (id);
alter table person_films add constraint FKavfmyayv2v0yutn7qnh2o7wkm foreign key (characters_id) references person (id);
alter table planet_films add constraint FKj6xfpgdqqmb34j880l60nsfcw foreign key (films_id) references film (id);
alter table planet_films add constraint FKb7b8v6em5vxkmigjqqk3kxctv foreign key (planets_id) references planet (id);
alter table planet_residents add constraint FKhashmp7rcgqdvrbecjsh09m5r foreign key (residents_id) references person (id);
alter table planet_residents add constraint FK7j18qhysxpxcqtujirava927t foreign key (planet_id) references planet (id);
alter table species add constraint FKp61wjv50m3nfvoke36v174sn5 foreign key (homeworld_id) references planet (id);
alter table species_films add constraint FK2t8l5jefsmxfxsxy49poro10v foreign key (films_id) references film (id);
alter table species_films add constraint FKi5t8kxgr865bol115vhpcrsb8 foreign key (species_id) references species (id);
alter table species_people add constraint FK5uaqwr63ov7wd1an62sukw908 foreign key (people_id) references person (id);
alter table species_people add constraint FK7soq9pv3s6djgtxmb7431fgee foreign key (species_id) references species (id);
alter table starship_films add constraint FKpnmpsm2g9bir1km1nufbaor4i foreign key (films_id) references film (id);
alter table starship_films add constraint FKjmrtlhumxa8gkjt3ufjvr5u0c foreign key (starships_id) references starship (id);
alter table starship_pilots add constraint FKmg96tf6y6o5aqaucqj38ep9fl foreign key (pilots_id) references person (id);
alter table starship_pilots add constraint FKj8woi4aqnwlx2tay4w7saq83y foreign key (starships_id) references starship (id);
alter table vehicle_films add constraint FKs8cfkhvkn8cv4yaxbm1u1rih7 foreign key (films_id) references film (id);
alter table vehicle_films add constraint FKfl30g9l5ocqbg7p3k9w5v25fb foreign key (vehicles_id) references vehicle (id);
alter table vehicle_pilots add constraint FKqimn856lkidkyajfbi4mm3xvy foreign key (pilots_id) references person (id);
alter table vehicle_pilots add constraint FKep6tpw2kgcwsnlkr1pb4qqq16 foreign key (vehicles_id) references vehicle (id);
